#!/usr/bin/env python

import telebot,sys,re

BOT_TOKEN=''
DESTINATION=sys.argv[1]
SUBJECT=sys.argv[2]
MESSAGE=re.sub(r'(\d{4})\.(\d{2})\.(\d{2})',r'\3/\2/\1', sys.argv[3])
MESSAGE = MESSAGE.replace('/n','\n')
tb = telebot.TeleBot(BOT_TOKEN)
tb.send_message(DESTINATION,SUBJECT + '\n' + MESSAGE)
